AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  BlockTable:
    Type: "AWS::Serverless::SimpleTable"
  VoteWatcher:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs8.10
      Handler: index.handler
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref VoteBlock
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /
            Method: post